name: /DATAT/miniconda3/envs/starter310
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ipykernel=6.29.5
  - ipython=8.35.0
  - jedi=0.19.2
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.16
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.51
  - psutil=5.9.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.16
  - python_abi=3.10
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==14.3.0
      - beautifulsoup4==4.13.4
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - codebleu==0.7.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.6.0
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - evaluate==0.4.3
      - filelock==3.18.0
      - fonttools==4.57.0
      - frozenlist==1.6.0
      - fsspec==2024.12.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - idna==3.10
      - jinja2==3.1.6
      - jiter==0.9.0
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lxml==5.3.2
      - markdown==3.10
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - multidict==6.4.3
      - multiprocess==0.70.16
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==2.2.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - ollama==0.5.1
      - openai==1.76.2
      - opencv-python-headless==4.12.0.88
      - pandas==2.2.3
      - peft==0.15.2
      - pillow==11.2.1
      - portalocker==3.1.1
      - propcache==0.3.1
      - protobuf==6.30.2
      - pyarrow==19.0.1
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.11
      - regex==2024.11.6
      - requests==2.32.3
      - rouge-score==0.1.2
      - sacrebleu==2.5.1
      - safetensors==0.5.3
      - scipy==1.15.3
      - sentry-sdk==2.27.0
      - setproctitle==1.3.6
      - simsimd==6.5.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - stringzilla==3.12.5
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tokenizers==0.21.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.51.3
      - tree-sitter==0.22.3
      - tree-sitter-python==0.23.6
      - triton==3.2.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - wandb==0.19.10
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yarl==1.20.0
prefix: /DATAT/miniconda3/envs/starter310
